config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    
  devise_scope :user do
    root :to => "devise/sessions#new"
  end
  resources :wishes, only: [:index, :create, :update, :destroy]
  resources :records, only: [:index, :create, :update, :destroy]
  resources :users, only: :show
  

end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MoneyWishList
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %link{href: "https://fonts.googleapis.com/css?family=Lato:400,700|Noto+Sans+JP:400,700", rel: "stylesheet"}/
  %body
    %header.header
      = render 'layouts/notifications'
      .header__title Money Wish List
      .header__right
        = link_to_unless_current "Wish List", wishes_path, class: "header__right--btn"
        = link_to_unless_current "Record List", records_path, class: "header__right--btn"
        = link_to_unless_current "Record chart", user_path(current_user.id), class: "header__right--btn"
        = link_to_unless_current "ログアウト", destroy_user_session_path, method: :delete, class: "header__right--btn"
    
    = yield

app/views/layouts/sub-layout.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MoneyWishList
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .wrapper
      = yield